import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Header from "@/components/header/Header";
import CustomFooter from "@/components/mobile/CustomFooter";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <ReactQueryProvider>

        <ThemeProvider attribute="class" defaultTheme="light">
          <Toaster
           
           />

          <Header />
          {/* <TestHeader/> */}
          {children}
          <CustomFooter />
          <Footer/>
        </ThemeProvider>
           </ReactQueryProvider>
      </body>
    </html>
  );
}
